export const catalogs = [
  {
    catalogName: 'Телефоны и гаджеты',
    catalogDatas: [
      {
        title: 'Гаджеты',
        gajetsItems: [
          'Планшеты',
          'Смарт часы',
          'Фитнес браслеты',
          'Очки виртуальной реальности',
          'Рации и радиостанции',
          'Умные весы',
        ],
      },
      {
        title: 'Аксессуары для телефонов',
        accessuarItems: [
          'Внешние аккумуляторы',
          'Держатели для смартфонов',
          'Зарядные устройства',
          'Игровые аксессуары',
          'USB кабель для телефона',
          'Карты памяти',
          'Моноподы для селфи',
          'Наушники и гарнитуры',
          'Защитные стекла для телефона',
          'Чехлы для телефонов',
        ],
      },
      {
        title: 'Телефоны',
        phoneItems: [
          'Смартфоны',
          'Смартфоны Apple',
          'Смартфоны Samsung',
          'Vivo',
          'OPPO',
          'Honor',
          'Xiaomi',
          'Huawei',
          'TECNO',
          'Игровые',
        ],
      },
      {title: 'Планшеты', tabletItems: ['ТОПовые планшеты'], id: 4},
      {title: 'Мониторы', displayItems: [''], id: 5},
      {title: 'Гарнитуры для PC', thingforPsItems: [''], id: 6},
    ],
    id: 1,
  },
  {
    catalogName: 'Техника для дома',
    catalogDatas: [
      {
        title: 'Швейный машинки',
        sweingItems: [
          'Chayka',
          'Aurora',
          'Janome',
          'Bernette',
          'Оверлоки',
          'Швейные наборы',
        ],
      },
      {
        title: 'Пылесосы',
        vacumCleanItems: [
          'Все марки пылесосов',
          'Пылесосы Samsung',
          'Пылесосы Gorenje',
          'Пылесосы Sencor',
          'Аквапылесос',
          'Беспроводные пылесосы',
          'Пылесосы с пылесборником',
          'Фильтры для пылесосов',
          'Пылесосы Artel',
        ],
      },
      {
        title: 'Стиральная машина',
        washingItems: [
          'Все марки стиральных машин',
          'Стиральные машины Whirlpool',
          'Стиральные машины Samsung',
          'Стиральные машины LG',
          'Бесшумные стиральные машинки',
          'Премиум класса стиральные машины',
        ],
      },
      {
        title: 'Газонокосилки',
        gresscutItems: [
          'IP камера',
          'Смарт часы',
          'Фитнес браслеты',
          'Очки виртуальной реальности',
          'Рации и радиостанции',
          'Умные весы',
        ],
      },
      {
        title: 'Гаджеты',
        gatjetsItems: [
          'IP камера',
          'Смарт часы',
          'Janome',
          'Bernette',
          'Оверлоки',
          'Швейные наборы',
        ],
      },
    ],
    id: 2,
  },
  {
    catalogName: 'Телевизоры и теле карты',
    catalogDatas: [],
    id: 3,
  },
  {
    catalogName: 'Офисная техника',
    catalogDatas: [],
    id: 4,
  },
  {
    catalogName: 'Компьютерная техника',
    catalogDatas: [],
    id: 5,
  },
  {
    catalogName: 'Товары для детей',
    catalogDatas: [],
    id: 6,
  },
  {
    catalogName: 'Фото и видео',
    catalogDatas: [],
    id: 7,
  },
  {
    catalogName: 'Электроника',
    catalogDatas: [],
    id: 8,
  },
  {
    catalogName: 'Красота и здоровье',
    catalogDatas: [],
    id: 9,
  },
  {
    catalogName: 'Спорт и увлечение',
    catalogDatas: [],
    id: 10,
  },
  {
    catalogName: 'Игровые приставки',
    catalogDatas: [],
    id: 11,
  },
]
